mybatis:
  mapper-locations: classpath:/mapper/**Mapper.xml
  type-aliases-package: com.bpg.bean,com.bpg.dao
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource